### ISSUE TITLE
Sensor performance

### ISSUE THREAD

**Issue by michaelshmitty** [ductsoup/Air-Quality-Sensor-Suite#2]
Hi Craig,

I couldn't find a way to message you privately. I wonder if Github even has this ability?

Anyways, we're working on a open source community project where hobbyists can build their own particulates sensor to raise awareness for the health issues surrounding small dust particles.
I learned a lot from your code, thanks for publishing this. I like the idea of using interrupts in particular.

How was your experience with these sensors compared to expensive (hundreds of dollars and above), professional devices? Is the data useful or did you find them to be inadequate for any real situations?

Cheers!

Michael

**Comment by ductsoup** [comment]
Michael,

Glad to help. Real world tested, think this can work for what you're doing.

I designed these to replace our failing commercial dust sensors and to give our building automation a better sense of what it feels (and smells) like to be working on the shop floor. Ours is a heavy industrial environment, we've got four of these installed and haven't had any problems at all aside from the occasional knucklehead unplugging them to poach a 120VAC outlet now and then. Honestly, I never expected the original prototype to last more than a week or two. When it didn't fail, we rolled them out in other areas.

Near as I can tell the sensor technology was developed in China where air quality is an ongoing concern. The documentation doesn't translate well but if you think through the missing and wrong words it's clear they've put a lot of thought into the design. The sensitivity and dynamic range is quite remarkable. Almost too much so.

Expect to have to log a bunch of data, understand your baseline then maybe tune the filter and sample time constants for your application to get a meaningful result. Any free IoT platform (adafruit.io, carriots/freeboard.io, etc.) can easily take the place of the commercial SCADA solution we use to help you do that.
