### ISSUE TITLE
Python Script Calling problem

### ISSUE THREAD

**Issue by mhrbsl** [ductsoup/Air-Quality-Sensor-Suite#3]
Hello friend.

I am using dragino Yun Shield with Arduino Mega2560. I made a project which is related with dht22 sensors. In this project, I read the values of sensors and send them to google spreadsheets. And now I want to read this values from OPC server. I have been trying to run your example codes about 1 week and I couldnt get any result. 

I am newbie at python coding. I noticed that I couldnt call python script from arduino side. When I try manually open the "modbus_tcp_slave.py" on putty, I get an error message. Could you please help me about this problem ?

**Comment by ductsoup** [comment]
Hi,

They python code was fully tested on an Arduino Yun, there could be some changes necessary for the shield you're using. Best to start by confirming the bridge example sketches work correctly. If you're still stuck maybe support at Dragino can help. Good luck.
